config/routes.rb
Ltabaseball::Application.routes.draw do
  devise_for :users

  resources :static_pages

  resources :static_pages
  root to: "static_pages#index"

end

app/models/static_page.rb
class StaticPage < ActiveRecord::Base
  attr_accessible :body, :title, :user_id
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  # GET /static_pages
  # GET /static_pages.json
  def index
    @static_pages = StaticPage.last

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @static_pages }
    end
  end

  # GET /static_pages/1
  # GET /static_pages/1.json
  def show
    @static_page = StaticPage.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @static_page }
    end
  end

  # GET /static_pages/new
  # GET /static_pages/new.json
  def new
    @static_page = StaticPage.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @static_page }
    end
  end

  # GET /static_pages/1/edit
  def edit
    @static_page = StaticPage.find(params[:id])
  end

  # POST /static_pages
  # POST /static_pages.json
  def create
    @static_page = StaticPage.new(params[:static_page])

    respond_to do |format|
      if @static_page.save
        format.html { redirect_to @static_page, notice: 'Static page was successfully created.' }
        format.json { render json: @static_page, status: :created, location: @static_page }
      else
        format.html { render action: "new" }
        format.json { render json: @static_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /static_pages/1
  # PUT /static_pages/1.json
  def update
    @static_page = StaticPage.find(params[:id])

    respond_to do |format|
      if @static_page.update_attributes(params[:static_page])
        format.html { redirect_to @static_page, notice: 'Static page was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @static_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /static_pages/1
  # DELETE /static_pages/1.json
  def destroy
    @static_page = StaticPage.find(params[:id])
    @static_page.destroy

    respond_to do |format|
      format.html { redirect_to static_pages_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_header.html.erb
<span>
  <h1 style="margin-bottom:-245px;font-style: italic;word-spacing: 10px;margin-top: 0px;height:100px;background-color:white;box-shadow: 0px 10px 20px #888;">
    <li class="dropdown" id="my-drop" style="list-style-type: none;display: initial;">
      <a href="#" class="dropdown header-link dropdown-toggle" data-toggle="dropdown">GAMES</a>
      <ul class="dropdown-menu">
        <li><a href="#">Today</a></li>
        <li><a href="#">Tomorrow</a></li>
        <li class="divider"></li>
        <li><a href="#">This Week</a></li>
      </ul>
    </li> | 

    <li class="dropdown" style="list-style-type: none;display: initial;">
      <a href="#" class="dropdown header-link dropdown-toggle" data-toggle="dropdown">DIVISIONS</a>
      <ul class="dropdown-menu">
        <li><a href="#collapsible1" class="accordion-toggle" data-parent="#menu1"><b>C Division</b></a></li>
        <li class="dropdown-submenu collapse" id="collapsible1">
          <a href="#">Schedule</a>
          <ul class="dropdown-menu">
            <li><a href="#div-c-sched" class="accordion-toggle" data-parent="#menu2"><b>Teams</b></a></li>
            <li class="collapse" id="div-c-sched">
              <a href="#" id="div-c-bel-sched">Belmont</a>
              <a href="#" id="div-c-brook-sched">Brookline</a>
              <a href="#" id="div-c-cam-sched">Cambridge</a>
              <a href="#" id="div-c-ever-sched">Everett</a>
              <a href="#" id="div-c-fram-sched">Framingham</a>
              <a href="#" id="div-c-grot-sched">Groton</a>
              <a href="#" id="div-c-marl-sched">Marlboro</a>
              <a href="#" id="div-c-med-sched">Medford</a>
              <a href="#" id="div-c-mel-sched">Melrose</a>
              <a href="#" id="div-c-new-sched">Newton</a>
              <a href="#" id="div-c-park-sched">Parkway</a>
              <a href="#" id="div-c-sud-sched">Sudbury</a>
              <a href="#" id="div-c-wake-sched">Wakefield</a>
              <a href="#" id="div-c-win-sched">Winchester</a>
            </li>
          </ul>
        </li>
        <li><a href="#"><b>B Division</b></a></li>
        <li><a href="#"><b>A Division</b></a></li>
        <li class="divider"></li>
        <li><a href="#"><b>Senior Division</b></a></li>
      </ul>
    </li>

    <a href="/" id="logo-link"><img src="/assets/logo.png" style="margin-bottom: -105px;position: relative;z-index: 10;"></a>
    <a href="<%=new_user_session_path%>" class="header-link">COACHES</a> | 
    <a href="#" class="header-link">ABOUT US</a> 
  </h1>
</span>
<div class="messagepop pop popfive">
    <%= render partial: '/static_pages/sched_fram_c' %>
</div>
<script language="javascript" type="text/javascript">
      function deselect() {
          $(".pop").slideFadeToggle(function() { 
              $("#div-c-fram-sched").removeClass("selected");
          });    
      }

      $(function() {
          $("#div-c-fram-sched").click(function() {
              if($(this).hasClass("selected")) {
                  deselect();               
              } else {
                  $(this).addClass("selected");
                  $(".pop").slideFadeToggle(function() { 
                      $("#email").focus();
                  });
              }
              return false;
          });

          $(".close").on('click', function() {
              deselect();
              return false;
          });
      });
      $.fn.slideFadeToggle = function(easing, callback) {
          return this.animate({ opacity: 'toggle', height: 'toggle' }, "fast", easing, callback);
      };

      $('.dropdown-toggle').dropdown();
      $('.dropdown-menu').each(function() {
          $(this).on('click', '.accordion-toggle', function(event) {
              event.stopPropagation();
              var $this = $(this);

              var parent = $this.data('parent');
              var actives = parent && $(parent).find('.collapse');

              // From bootstrap itself
              if (actives && actives.length) {
                  hasData = actives.data('collapse');
                  if (hasData && hasData.transitioning) return;
                  actives.collapse('hide');
              }

              var target = $this.attr('data-target') || (href = $this.attr('href')) && href.replace(/.*(?=#[^\s]+$)/, ''); //strip for ie7

              $(target).collapse('toggle');
              return false;
          });
      });
      deselect();
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="shortcut icon" href="/assets/logo.png"></link>
    <title>Lou Tompkins All Star Baseball, Inc</title>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, min-width=device-width, max-width=device-width, maximum-scale=2">
    <%= yield(:head) %>
  </head>
  <body id="body" style="background-color:#eee">
    <%= render 'layouts/header' %>
    <div class="container-fluid" style="margin-top:208px">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/static_pages/_form.html.erb
<%= form_for(@static_page) do |f| %>
  <% if @static_page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@static_page.errors.count, "error") %> prohibited this static_page from being saved:</h2>

      <ul>
      <% @static_page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/static_pages/edit.html.erb
<h1>Editing static_page</h1>

<%= render 'form' %>

<%= link_to 'Show', @static_page %> |
<%= link_to 'Back', static_pages_path %>

app/views/static_pages/index.html.erb
<div id="carousel-example-generic" class="carousel fade" data-ride="carousel">

  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item active">
      <img src="/assets/game_one.jpg" alt="">
      <div class="carousel-caption">
        <h1 style="font-size: 47px;float:left;text-shadow: 0.1em 0.1em 0.2em black;">WELCOME TO THE <br>LEAGUE OF CHAMPIONS!</h1>
      </div>
    </div>
    <div class="item">
      <img src="/assets/game_two.jpg" alt="">
      <div class="carousel-caption">
        <h1 style="font-size: 47px;float:left;text-shadow: 0.1em 0.1em 0.2em black;">WELCOME TO THE <br>LEAGUE OF CHAMPIONS!</h1>
      </div>
    </div>
    <div class="item">
      <img src="/assets/game_three.png" alt="">
      <div class="carousel-caption">
        <h1 style="font-size: 47px;float:left;text-shadow: 0.1em 0.1em 0.2em black;">WELCOME TO THE <br>LEAGUE OF CHAMPIONS!</h1>
      </div>
    </div>
    <div class="item">
      <img src="/assets/game_four.jpg" alt="">
      <div class="carousel-caption">
        <h1 style="font-size: 47px;float:left;text-shadow: 0.1em 0.1em 0.2em black;">WELCOME TO THE <br>LEAGUE OF CHAMPIONS!</h1>
      </div>
    </div>
  </div>
</div>
<br><br>
<!-- Main Table to hold sections below blog, twitter, and rest of items below carousel -->
<table>
  <tr>
    <td>

      <table style="margin-left:120px;background-color:white;max-width: 620px;border-top:0px;box-shadow: 0px 10px 20px #888;">
        <tr>
          <td><h3 style="margin-left:10px">Welcome to the Lou Tompkins All Star Baseball League</h3><br></td>
        </tr>
        <tr>
          <% if @static_pages.present? %>
            <td><h5 style="margin-left:10px">From the desk of LTA President, Joe Rushing.</h5></td>
          </tr>
          <tr>
              <td><h3 style="margin-left:10px"><%= @static_pages.title %></h3></td>
            </tr>
            <tr>
              <td><p style="margin-left:10px"><%= @static_pages.body.html_safe %></p></td>
            </tr>
            <tr>
              <td><b style="margin-left:10px">Joe Rushing, President</b></td>
            </tr>
            <tr>
              <td style="margin-left:10px">
            <br><br><%= link_to 'View More', static_pages_path %></td>
          <% end %>
        </tr>
      </table>

    </td>
    <td style="float:right;margin-right:100px">

      <table style="margin-left:20px;background-color:white;max-width: 620px;border-top:0px;box-shadow: 0px 10px 20px #888;">
        <tr>
          <td><b>The latest updates from @LTABasball</b>
        <br><br></td>
        </tr>
        <tr>
          <td style="border-bottom:1px solid"><b>06/24 1:34PM</b><br><br><img src="/assets/logo.png" style="width: 30px;position: relative;z-index: 10;"><b>@LTABaseball</b> Today's game in Concord has been postponed. It will be rescheduled for a date further into the season. Rest hard today boys, and play hard tomorrow. Good Luck!<br><br></td>
        </tr><br><tr>
          <td style="border-bottom:1px solid"><b>06/22 12:03PM</b><br><br><img src="/assets/logo.png" style="width: 30px;position: relative;z-index: 10;"><b>@LTABaseball</b> The hot game of the week, Framingham versus Winchester. This long historic rivalry has its roots back when Jordan Rushing's team beath them up in the 2000 Championship Game. Looking forward to a great game! Good Luck!<br><br></td>
        </tr>
      </table>
    </td>
  </tr>
  <tr>
    <td>
      <img src="/assets/sign_one.jpg" style="margin-top: 5%;width: 90%;margin-left: 5%;box-shadow: 0px 10px 20px #888;">
    </td>
    <td>
      <img src="/assets/sign_two.jpg" style="margin-top: 5%;width: 90%;margin-left: 5%;box-shadow: 0px 10px 20px #888;">
    </td>
  </tr>
</table>

<br />
<script language="javascript" type="text/javascript">
$('.carousel').carousel({
  interval: 10000,
  pause: false
})
</script>

app/views/static_pages/new.html.erb
<h1>New static_page</h1>

<%= render 'form' %>

<%= link_to 'Back', static_pages_path %>

app/views/static_pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @static_page.title %>
</p>

<p>
  <b>Body:</b>
  <%= @static_page.body %>
</p>

<p>
  <b>User:</b>
  <%= @static_page.user_id %>
</p>


<%= link_to 'Edit', edit_static_page_path(@static_page) %> |
<%= link_to 'Back', static_pages_path %>